language: ruby
rvm:
  - 2.2
  - 2.1
  - ruby-head
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle exec rspec
#gemfile:
#  - gemfiles/rails41.gemfile
#  - gemfiles/rails42.gemfile
#  - gemfiles/rails50.gemfile
